theme: jekyll-theme-cayman
title: Twitch Badge Collector
url: "https://tbc.bluewarn.dev"
description: Collect and view chat with special badges in Twitch Chat!
show_downloads: true
google_analytics: UA-194964708-4


github:
  zip_url: https://github.com/Deepbluewarn/twitch_badge_collector/releases/latest/download/twitch_badge_collector.zip
  another_url: https://github.com/Deepbluewarn/twitch_badge_collector/releases/latest/download/twitch_badge_collector.zip
